### PR TITLE
Add authentification arg to run command

### PR DESCRIPTION
**Pull request by PhilippeMoussalli**
The cloud credential arguments were only present to the `compile` command and not the `run` one. This PR fixes this issue, @Hakimovich99

### CODE REVIEW

**Comment by RobbeSneyders** [comment]
Can we still test the compile command as well? Otherwise @GeorgesLorre will be depressed.

**Comment by PhilippeMoussalli** [comment]
> Can we still test the compile command as well? Otherwise @GeorgesLorre will be depressed.

haha sure, added it

**Comment by GeorgesLorre** [comment]
> Can we still test the compile command as well? Otherwise @GeorgesLorre will be depressed.

only 95%+ test coverage will cure my depression

**Review by RobbeSneyders — APPROVED** [review]
Thanks @PhilippeMoussalli!

0.5% difference in test coverage. Deep down @GeorgesLorre will be at least a little bit pleased.

**Pull request merged**
