### PR TITLE
Enable GPU for local runner

### PR DESCRIPTION
**Pull request by PhilippeMoussalli**
PR that adds GPU resource for the local runner when specified in the componentOP 

based on: 
https://docs.docker.com/compose/gpu-support/

### CODE REVIEW

**Comment by RobbeSneyders** [comment]
Thanks @PhilippeMoussalli, have you been able to test this?

**Comment by PhilippeMoussalli** [comment]
> Thanks @PhilippeMoussalli, have you been able to test this?

Yes (partially). 

```
services:
  test:
    image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
```

Tested this on a VM and it showed that there is an available GPU

**Comment by PhilippeMoussalli** [comment]
> > Thanks @PhilippeMoussalli, have you been able to test this?
> 
> Yes (partially).
> 
> ```
> services:
>   test:
>     image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
>     command: nvidia-smi
>     deploy:
>       resources:
>         reservations:
>           devices:
>           - capabilities:
>             - gpu
>             count: 1
>             driver: nvidia
> ```
> 
> Tested this on a VM with GPU and it showed that there is an available GPU

Marc Tested this as well (manually) and it seems to be doing the job

**Comment by RobbeSneyders** [comment]
Ok thanks!

**Review by RobbeSneyders — APPROVED** [review]

**Pull request merged**
