### PR TITLE
Enable write components to cache

### PR DESCRIPTION
**Pull request by PhilippeMoussalli**
Fixes https://github.com/ml6team/fondant/issues/813

### CODE REVIEW

**Review by GeorgesLorre — APPROVED** [review]
Easy enough

**Comment by RobbeSneyders** [comment]
As discussed during standup, not sure if it makes sense to create a manifest for a write component, since it should not output a dataset.

I would also assume that the manifest it produces, points to a non-existing index. Since the index reference in the manifest is updated, but the index is not actually written.

**Comment by PhilippeMoussalli** [comment]
> As discussed during standup, not sure if it makes sense to create a manifest for a write component, since it should not output a dataset.
> 
> I would also assume that the manifest it produces, points to a non-existing index. Since the index reference in the manifest is updated, but the index is not actually written.

Makes sense, changed the approach. For read/transform components we write the cache file with reference to the cached manifest path, for write components we simply write the same file but with an empty string (no reference) since there is no written manifest. The cache estimation still occurs based on the cache key value

**Review by RobbeSneyders — APPROVED** [review]
Thanks!

**Pull request merged**
